# Generated by Django 5.1.2 on 2024-10-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('thumbnail_movie', models.ImageField(blank=True, null=True, upload_to='thumbnails/movies/')),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description available')),
                ('genre', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('thumbnail_tvshow', models.ImageField(blank=True, null=True, upload_to='thumbnails/tvshows/')),
                ('number_of_seasons', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_episode', models.ImageField(blank=True, null=True, upload_to='thumbnails/episodes/')),
                ('video_url', models.URLField()),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tvshow')),
            ],
        ),
    ]
